### ISSUE TITLE
LoadB doesn't load byte value after second use

### ISSUE THREAD

**Issue by Spike433** [izuzak/FRISCjs#17]
MNO PUSH R0
	PUSH R1
	PUSH R2
	LOADB R0,(1000) ; 4 is normally loaded
	**LOADB R1,(1001)** ; but on this address it reads 0 instead of 3

	
	MOVE 0,R2
	
PET ADD R0,R2,R2
	SUB R1,1,R1
	JR_NZ PET
	
GOT STOREB R2,(1002)
    LOAD R3,(1002)
	POP R2 
	POP R1
	POP R0
	
	RET
	
	`ORG 1000
	DB %D 4  ;ok 
	**DB %D 3**  ; fail
	DB 0

**Comment by izuzak** [comment]
Hey, @Spike433 👋  Thanks for reaching out and sorry for the very long delay in getting back to you on this. 

Please correct me if I'm wrong, but as far as I can tell -- you're seeing expected behavior. When you do this:

```
`ORG 1000
DB %D 4  ;ok 
DB %D 3 ; fail
DB 0
```

then on location `1000` in memory there will be the value `4`. However, the value `3` will be defined on the address `1004`, not on `1001`. This is due to the concept of data alignment ("poravnavanje adresa"). The address used for DB, DH and DW commands must be divisible by 4. 

So, after `DB %D 4` executes -- the next address is 1001, but that's not divisible by 4 and the next address divisible by 4 is 1004, so address 1004 is used for the execution of `DB %D 3 ; fail`.

Does that help and make sense? It's possible I'm mis-remembering something since I took the course many years ago. If I am mis-remembering -- please let me know.

You should be able to get the behavior you want with a slight modification to this:

```
`ORG 1000
DB %D 4,3
DB 0
```

Now, because both values are a part of the same command -- they are loaded on addresses 1000 and 1001.

**Comment by Spike433** [comment]
It makes sense and it is correct, at that moment I was sure it was bug.
